on:
  push:
    paths: ['R/data-objects.R']

name: bench-marks

jobs:
  bench-marks:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - name: Install rirods
        uses: actions/checkout@v3
        with:
          path: rirods

      - name: Install irods_demo
        uses: actions/checkout@v3
        with:
          repository: irods/irods_demo
          path: irods_demo

      - name: Setup iRODS demo
        run: |
          cd ./irods_demo
          git submodule update --init
          docker-compose up -d nginx-reverse-proxy

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        working-directory: ./rirods
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore(repos = c(CRAN = "https://cloud.r-project.org"))

      - name: Run bench mark and render Rmarkdown
        working-directory: ./rirods
        run: |
          PKG_PATH=$(pwd)
          BENCH_PATH=$(pwd)/inst/bench
          cd ${BENCH_PATH}
          Rscript run-bench.R main ${BENCH_PATH} irods/irods_client_library_rirods HEAD 5
          Rscript run-bench.R dev ${BENCH_PATH} ${PKG_PATH} ${{ github.sha }} 5
          Rscript -e "install.packages('knitr'); knitr::knit(file.path(getwd(), 'README.Rmd'), file.path(getwd(), 'README.md'))"
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit ${BENCH_PATH[*]/.Rmd/.md/.tsv} -m 'Benchmark results' || echo "No changes to commit"
          git pull --rebase
          git push origin || echo "No changes to commit"
